# Railway deployment configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "uvicorn back.main:app --host 0.0.0.0 --port $PORT"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NIXPACKS_PYTHON_VERSION = "3.11"
